2019-09-14 14:12:03,288 INFO - root - Initialising application
2019-09-14 14:12:03,297 INFO - root - Initialise global hotkeys
2019-09-14 14:12:03,297 INFO - config-manager - No configuration found - creating new one
2019-09-14 14:12:03,304 INFO - config-manager - Configuration changed - rebuilding in-memory structures
2019-09-14 14:12:03,305 INFO - config-manager - Persisting configuration
2019-09-14 14:12:03,305 INFO - config-manager - Finished persisting configuration - no errors
2019-09-14 14:12:03,305 INFO - service - Starting service
2019-09-14 14:12:03,366 INFO - iomediator - Created IoMediator instance, current interface is: <XRecordInterface(XInterface-thread, initial daemon)>
2019-09-14 14:12:03,378 INFO - interface - XRecord interface thread starting
2019-09-14 14:12:03,379 INFO - service - Service now marked as running
2019-09-14 14:12:03,397 INFO - root - Displaying configuration window
2019-09-14 14:12:03,964 INFO - root - Entering main()
2019-09-14 14:12:57,166 INFO - config-manager - Configuration changed - rebuilding in-memory structures
2019-09-14 14:12:57,166 INFO - config-manager - Persisting configuration
2019-09-14 14:12:57,166 INFO - config-manager - Backing up existing config file
2019-09-14 14:12:57,168 INFO - config-manager - Finished persisting configuration - no errors
2019-09-14 14:13:02,290 INFO - config-manager - Configuration changed - rebuilding in-memory structures
2019-09-14 14:13:02,290 INFO - config-manager - Persisting configuration
2019-09-14 14:13:02,290 INFO - config-manager - Backing up existing config file
2019-09-14 14:13:02,292 INFO - config-manager - Finished persisting configuration - no errors
2019-09-14 14:13:06,230 INFO - config-manager - Configuration changed - rebuilding in-memory structures
2019-09-14 14:13:06,230 INFO - config-manager - Persisting configuration
2019-09-14 14:13:06,230 INFO - config-manager - Backing up existing config file
2019-09-14 14:13:06,231 INFO - config-manager - Finished persisting configuration - no errors
2019-09-14 14:13:10,243 INFO - config-manager - Configuration changed - rebuilding in-memory structures
2019-09-14 14:13:10,243 INFO - config-manager - Persisting configuration
2019-09-14 14:13:10,243 INFO - config-manager - Backing up existing config file
2019-09-14 14:13:10,247 INFO - config-manager - Finished persisting configuration - no errors
2019-09-14 14:13:13,609 INFO - config-manager - Configuration changed - rebuilding in-memory structures
2019-09-14 14:13:13,609 INFO - config-manager - Persisting configuration
2019-09-14 14:13:13,609 INFO - config-manager - Backing up existing config file
2019-09-14 14:13:13,610 INFO - config-manager - Finished persisting configuration - no errors
2019-09-14 14:14:53,043 INFO - config-manager - Configuration changed - rebuilding in-memory structures
2019-09-14 14:14:59,875 INFO - config-manager - Configuration changed - rebuilding in-memory structures
2019-09-14 14:14:59,876 INFO - config-manager - Persisting configuration
2019-09-14 14:14:59,876 INFO - config-manager - Backing up existing config file
2019-09-14 14:14:59,878 INFO - config-manager - Finished persisting configuration - no errors
2019-09-14 14:15:02,682 INFO - root - Displaying configuration window
2019-09-14 14:15:06,485 INFO - config-manager - Configuration changed - rebuilding in-memory structures
2019-09-14 14:15:06,486 INFO - config-manager - Persisting configuration
2019-09-14 14:15:06,486 INFO - config-manager - Backing up existing config file
2019-09-14 14:15:06,487 INFO - config-manager - Finished persisting configuration - no errors
2019-09-14 14:19:33,404 INFO - root - Displaying configuration window
2019-09-14 14:20:49,101 INFO - config-manager - Save autostart settings: AutostartSettings(desktop_file_name='autokey-gtk.desktop', switch_show_configure=False)
2019-09-14 14:20:49,102 INFO - config-manager - Used 'Exec' line in desktop file: Exec=autokey-gtk
2019-09-14 14:20:49,172 INFO - config-manager - Configuration changed - rebuilding in-memory structures
2019-09-14 14:20:49,172 INFO - config-manager - Persisting configuration
2019-09-14 14:20:49,172 INFO - config-manager - Backing up existing config file
2019-09-14 14:20:49,174 INFO - config-manager - Finished persisting configuration - no errors
2019-09-14 14:23:12,154 INFO - config-manager - Configuration changed - rebuilding in-memory structures
2019-09-14 14:23:12,183 INFO - config-manager - Configuration changed - rebuilding in-memory structures
2019-09-14 14:23:12,186 INFO - config-manager - Persisting configuration
2019-09-14 14:23:12,187 INFO - config-manager - Backing up existing config file
2019-09-14 14:23:12,193 INFO - config-manager - Finished persisting configuration - no errors
2019-09-14 14:23:12,210 ERROR - interface - Got BadWindow error while requesting window information.
Traceback (most recent call last):
  File "/usr/lib/python3.7/site-packages/autokey/interface.py", line 1074, in get_window_info
    return self._get_window_info(window, traverse)
  File "/usr/lib/python3.7/site-packages/autokey/interface.py", line 1080, in _get_window_info
    new_wm_title = self._try_get_window_title(window)
  File "/usr/lib/python3.7/site-packages/autokey/interface.py", line 1128, in _try_get_window_title
    atom = self._try_read_property(window, self.__VisibleNameAtom)
  File "/usr/lib/python3.7/site-packages/autokey/interface.py", line 1145, in _try_read_property
    return window.get_property(property_name, 0, 0, 255)
  File "/usr/lib/python3.7/site-packages/Xlib/xobject/drawable.py", line 461, in get_property
    long_length = length)
  File "/usr/lib/python3.7/site-packages/Xlib/protocol/rq.py", line 1369, in __init__
    self.reply()
  File "/usr/lib/python3.7/site-packages/Xlib/protocol/rq.py", line 1389, in reply
    raise self._error
Xlib.error.BadWindow: <class 'Xlib.error.BadWindow'>: code = 3, resource_id = <class 'Xlib.xobject.resource.Resource'>(0x0140c9c5), sequence_number = 3115, major_opcode = 20, minor_opcode = 0
2019-09-14 14:23:12,213 ERROR - interface - Got BadWindow error while requesting window information.
Traceback (most recent call last):
  File "/usr/lib/python3.7/site-packages/autokey/interface.py", line 1074, in get_window_info
    return self._get_window_info(window, traverse)
  File "/usr/lib/python3.7/site-packages/autokey/interface.py", line 1080, in _get_window_info
    new_wm_title = self._try_get_window_title(window)
  File "/usr/lib/python3.7/site-packages/autokey/interface.py", line 1128, in _try_get_window_title
    atom = self._try_read_property(window, self.__VisibleNameAtom)
  File "/usr/lib/python3.7/site-packages/autokey/interface.py", line 1145, in _try_read_property
    return window.get_property(property_name, 0, 0, 255)
  File "/usr/lib/python3.7/site-packages/Xlib/xobject/drawable.py", line 461, in get_property
    long_length = length)
  File "/usr/lib/python3.7/site-packages/Xlib/protocol/rq.py", line 1369, in __init__
    self.reply()
  File "/usr/lib/python3.7/site-packages/Xlib/protocol/rq.py", line 1389, in reply
    raise self._error
Xlib.error.BadWindow: <class 'Xlib.error.BadWindow'>: code = 3, resource_id = <class 'Xlib.xobject.resource.Resource'>(0x0140cbc6), sequence_number = 3117, major_opcode = 20, minor_opcode = 0
2019-09-14 14:23:12,215 ERROR - interface - Got BadWindow error while requesting window information.
Traceback (most recent call last):
  File "/usr/lib/python3.7/site-packages/autokey/interface.py", line 1074, in get_window_info
    return self._get_window_info(window, traverse)
  File "/usr/lib/python3.7/site-packages/autokey/interface.py", line 1080, in _get_window_info
    new_wm_title = self._try_get_window_title(window)
  File "/usr/lib/python3.7/site-packages/autokey/interface.py", line 1128, in _try_get_window_title
    atom = self._try_read_property(window, self.__VisibleNameAtom)
  File "/usr/lib/python3.7/site-packages/autokey/interface.py", line 1145, in _try_read_property
    return window.get_property(property_name, 0, 0, 255)
  File "/usr/lib/python3.7/site-packages/Xlib/xobject/drawable.py", line 461, in get_property
    long_length = length)
  File "/usr/lib/python3.7/site-packages/Xlib/protocol/rq.py", line 1369, in __init__
    self.reply()
  File "/usr/lib/python3.7/site-packages/Xlib/protocol/rq.py", line 1389, in reply
    raise self._error
Xlib.error.BadWindow: <class 'Xlib.error.BadWindow'>: code = 3, resource_id = <class 'Xlib.xobject.resource.Resource'>(0x0140f32c), sequence_number = 3119, major_opcode = 20, minor_opcode = 0
2019-09-14 14:23:12,217 ERROR - interface - Got BadWindow error while requesting window information.
Traceback (most recent call last):
  File "/usr/lib/python3.7/site-packages/autokey/interface.py", line 1074, in get_window_info
    return self._get_window_info(window, traverse)
  File "/usr/lib/python3.7/site-packages/autokey/interface.py", line 1080, in _get_window_info
    new_wm_title = self._try_get_window_title(window)
  File "/usr/lib/python3.7/site-packages/autokey/interface.py", line 1128, in _try_get_window_title
    atom = self._try_read_property(window, self.__VisibleNameAtom)
  File "/usr/lib/python3.7/site-packages/autokey/interface.py", line 1145, in _try_read_property
    return window.get_property(property_name, 0, 0, 255)
  File "/usr/lib/python3.7/site-packages/Xlib/xobject/drawable.py", line 461, in get_property
    long_length = length)
  File "/usr/lib/python3.7/site-packages/Xlib/protocol/rq.py", line 1369, in __init__
    self.reply()
  File "/usr/lib/python3.7/site-packages/Xlib/protocol/rq.py", line 1389, in reply
    raise self._error
Xlib.error.BadWindow: <class 'Xlib.error.BadWindow'>: code = 3, resource_id = <class 'Xlib.xobject.resource.Resource'>(0x01411a03), sequence_number = 3121, major_opcode = 20, minor_opcode = 0
2019-09-14 14:24:25,347 INFO - root - Initialising application
2019-09-14 14:24:25,355 INFO - root - Initialise global hotkeys
2019-09-14 14:24:25,356 INFO - config-manager - Loading config from existing file: /home/jll/.config/autokey/autokey.json
2019-09-14 14:24:25,364 INFO - config-manager - Configuration changed - rebuilding in-memory structures
2019-09-14 14:24:25,364 INFO - config-manager - Successfully loaded configuration
2019-09-14 14:24:25,365 INFO - service - Starting service
2019-09-14 14:24:25,430 INFO - iomediator - Created IoMediator instance, current interface is: <XRecordInterface(XInterface-thread, initial daemon)>
2019-09-14 14:24:25,439 INFO - interface - XRecord interface thread starting
2019-09-14 14:24:25,440 INFO - service - Service now marked as running
2019-09-14 14:24:25,461 INFO - root - Displaying configuration window
2019-09-14 14:24:26,172 INFO - root - Entering main()
2019-09-14 14:25:15,034 INFO - config-manager - Configuration changed - rebuilding in-memory structures
2019-09-14 14:25:15,059 INFO - config-manager - Configuration changed - rebuilding in-memory structures
2019-09-14 14:25:15,060 INFO - config-manager - Persisting configuration
2019-09-14 14:25:15,061 INFO - config-manager - Backing up existing config file
2019-09-14 14:25:15,067 INFO - config-manager - Finished persisting configuration - no errors
2019-09-14 14:25:15,077 ERROR - interface - Got BadWindow error while requesting window information.
Traceback (most recent call last):
  File "/usr/lib/python3.7/site-packages/autokey/interface.py", line 1074, in get_window_info
    return self._get_window_info(window, traverse)
  File "/usr/lib/python3.7/site-packages/autokey/interface.py", line 1080, in _get_window_info
    new_wm_title = self._try_get_window_title(window)
  File "/usr/lib/python3.7/site-packages/autokey/interface.py", line 1128, in _try_get_window_title
    atom = self._try_read_property(window, self.__VisibleNameAtom)
  File "/usr/lib/python3.7/site-packages/autokey/interface.py", line 1145, in _try_read_property
    return window.get_property(property_name, 0, 0, 255)
  File "/usr/lib/python3.7/site-packages/Xlib/xobject/drawable.py", line 461, in get_property
    long_length = length)
  File "/usr/lib/python3.7/site-packages/Xlib/protocol/rq.py", line 1369, in __init__
    self.reply()
  File "/usr/lib/python3.7/site-packages/Xlib/protocol/rq.py", line 1389, in reply
    raise self._error
Xlib.error.BadWindow: <class 'Xlib.error.BadWindow'>: code = 3, resource_id = <class 'Xlib.xobject.resource.Resource'>(0x01800401), sequence_number = 342, major_opcode = 20, minor_opcode = 0
2019-09-14 14:25:15,089 ERROR - interface - Got BadWindow error while requesting window information.
Traceback (most recent call last):
  File "/usr/lib/python3.7/site-packages/autokey/interface.py", line 1074, in get_window_info
    return self._get_window_info(window, traverse)
  File "/usr/lib/python3.7/site-packages/autokey/interface.py", line 1080, in _get_window_info
    new_wm_title = self._try_get_window_title(window)
  File "/usr/lib/python3.7/site-packages/autokey/interface.py", line 1128, in _try_get_window_title
    atom = self._try_read_property(window, self.__VisibleNameAtom)
  File "/usr/lib/python3.7/site-packages/autokey/interface.py", line 1145, in _try_read_property
    return window.get_property(property_name, 0, 0, 255)
  File "/usr/lib/python3.7/site-packages/Xlib/xobject/drawable.py", line 461, in get_property
    long_length = length)
  File "/usr/lib/python3.7/site-packages/Xlib/protocol/rq.py", line 1369, in __init__
    self.reply()
  File "/usr/lib/python3.7/site-packages/Xlib/protocol/rq.py", line 1389, in reply
    raise self._error
Xlib.error.BadWindow: <class 'Xlib.error.BadWindow'>: code = 3, resource_id = <class 'Xlib.xobject.resource.Resource'>(0x01800460), sequence_number = 344, major_opcode = 20, minor_opcode = 0
2019-09-14 14:25:31,985 INFO - root - Displaying configuration window
2019-09-14 14:27:00,892 INFO - config-manager - Configuration changed - rebuilding in-memory structures
2019-09-14 14:27:00,910 INFO - config-manager - Configuration changed - rebuilding in-memory structures
2019-09-14 14:27:00,910 INFO - config-manager - Persisting configuration
2019-09-14 14:27:00,911 INFO - config-manager - Backing up existing config file
2019-09-14 14:27:00,914 INFO - config-manager - Finished persisting configuration - no errors
